// Platform-specific headers
#ifdef _WIN32
#include <windows.h>
#elif defined(__APPLE__)
#include <mach-o/dyld.h>
#elif defined(__linux__)
#include <unistd.h>
#include <limits.h>
#endif

#include "Engine/io/AssetFileSystem.h"
#include "config.h"  // Generated by CMake

// to read the file
#include <fstream>

namespace GAMEDEV_ENGINE
{
    std::filesystem::path AssetFileSystem::GetExecutableFolder() const
    {
#ifdef _WIN32
        // Windows
        wchar_t buf[MAX_PATH];
        GetModuleFileNameW(NULL, buf, MAX_PATH);
        return std::filesystem::path(buf).remove_filename();

#elif defined(__APPLE__)
        // macOS
        uint32_t size = 0;
        _NSGetExecutablePath(nullptr, &size);
        std::string tmp(size, '\0');
        _NSGetExecutablePath(tmp.data(), &size);
        return std::filesystem::weakly_canonical(
            std::filesystem::path(tmp)
        ).remove_filename();

#elif defined(__linux__)
        // Linux
        return std::filesystem::weakly_canonical(
            std::filesystem::path("/proc/self/exe")
        ).remove_filename();

#else
#error "Unsupported platform"
#endif
    }

    std::filesystem::path AssetFileSystem::GetAssetsFolder() const
    {
        // ✅ Try development path first
#ifdef ASSETS_ROOT
        auto devPath = std::filesystem::path(ASSETS_ROOT);
        if (std::filesystem::exists(devPath)) {
            return devPath;  // Found in development!
        }
#endif

        // ✅ Fall back to runtime path (next to exe)
        return std::filesystem::weakly_canonical(
            GetExecutableFolder() / "assets"
        );
    }

    std::vector<char> AssetFileSystem::LoadFile(const std::filesystem::path& path)
    {
        std::ifstream file(path, std::ios::binary | std::ios::ate);
        if (!file.is_open())
        {
            return {};
        }
        auto size = file.tellg();
        file.seekg(0);

        std::vector<char> buffer(size);
        
        if (!file.read(buffer.data(), size))
        {
            return {};
        }
        
        return buffer;

    }

    std::vector<char> AssetFileSystem::LoadAssetFile(const std::string& relativepath)
    {
        return LoadFile(GetAssetsFolder() / relativepath);
    }

    std::string AssetFileSystem::LoadAssetFileText(const std::string& relativepath)
    {
        auto buffer = LoadAssetFile(relativepath);
        return std::string(buffer.begin(), buffer.end());
    }
}